export default {
  quiz: 'Quiz',
  quiz_complete: 'Quiz Complete',
  alwaysUseDevicesKeyboard: "Always Use Device's Keyboard",
  share: 'Share Lexicon with Others',
  'app_name': 'Lexicon',
  'facebook_app_id': '823567401104289',
  'threads': 'Threads',
  'tagline': 'Language Learning Buddy',
  'get_started': 'get started',
  'login': 'Login',
  'or_str': 'or',
  'connect_with_google': 'CONNECT WITH GOOGLE',
  'connect_with_facebook': 'CONNECT WITH FACEBOOK',
  'what_native_language': 'What language do you speak natively?',
  'what_learning_language': 'What language would you like to learn?',
  'request_a_new_language': 'Request a New Language',
  'language': 'Language',
  'confirm': 'confirm',
  'what_score': 'How quickly would you like to learn?',
  'offline_mode': 'Offline Mode',
  'explain_offline': 'This allows you to learn from a lesson while you are not connected to the internet.',
  'download': 'Download',
  'search': 'search',
  'no_review': 'Nothing to see here, go to Learn to get started',
  'no_threads': 'Nothing to see here, go to Search to get started',
  'no_search': 'Nothing to see here, come back later for more results',
  'create_profile': 'Create Profile',
  'settings': 'Settings',
  'test_favorites': 'Test Favorites',
  'test_all': 'Test All',
  'audio': 'Audio',
  'chapter': 'Chapter',
  'exit_session': 'Exit Session',
  'explain_exit': 'You are in the middle of a session. You will lost any unsaved progress. Are you sure you would like to exit?.',
  'report': 'Report an Issue',
  'feedback': 'Please provide feedback…',
  'ignore': 'Ignore',
  'skip': 'Skip',
  'tip': 'Tip',
  'tip_for': 'Tip for: ',
  'close': 'done',
  'favorite': 'Favorite',
  'continue_str': 'continue',
  'you_mastered': 'You have mastered the lesson!',
  'earned_point': 'You have earned a point for getting every question correct!',
  'explain_points': 'In order to start earning points and badges you must create a profile.',
  'keep_reviewing': 'keep reviewing',
  'keep_learning': 'keep learning',
  'back_to_overview': 'back to overview',
  'back_to_lessons': 'back to lessons',
  'translate_this_phrase': 'Translate this phrase',
  'record_the_translation': 'Record the translation',
  'pick_the_translation': 'Pick the correct translation',
  'are_you_sure': 'Are you sure',
  'explain_clear': 'You are about to clear all app data. This action cannot be undone.',
  'check': 'check',
  'translate': 'translate',
  'name': 'Name',
  'review': 'Review',
  'lesson': 'Lesson',
  'you_are_correct': 'You are correct!',
  'nailed_it': 'You nailed it!',
  'you_are_on_a_roll': 'You are on a roll!',
  'you_are_incorrect': 'Oops, that’s not correct\nYou will see this word again soon',
  'feedback_please': 'Please provide detailed feedback on the issue.',
  'complete': 'Complete',
  'all_for_master': 'You need to get all answers correct to master this lesson.',
  'all_for_point': 'You need to get all answers correct to earn a point.',
  'search_vocab': 'Search all vocabulary',
  'email': 'Email',
  'password': 'Password',
  'try_again': 'Please try again.',
  'provide_language': 'Please provide the name of the language you would like us to add.',
  'rate_lexicon': 'Rate Lexicon',
  'arabic': 'Arabic',
  'catalan': 'Catalan',
  'chinese_cantonese': 'Chinese - Cantonese',
  'chinese_mandarin': 'Chinese - Mandarin',
  'english': 'English',
  'german': 'German',
  'greek': 'Greek',
  'italian': 'Italian',
  'french': 'French',
  'japanese': 'Japanese',
  'korean': 'Korean',
  'polish': 'Polish',
  'russian': 'Russian',
  'spanish': 'Spanish',
  'learn': 'learn',
  'thank_you': 'Thank you for your feedback!',
  'cannot_connect': 'Cannot connect to server',
  'chat': 'Chat',
  'thanks_again': 'Thank you for your request. We will try to add that language as soon as possible.',
  'click_to_respond': 'Click to resend',
  'thread': 'Thread',
  'unsent': 'UNSENT',
  'points_per_day': '{0} points per day',
  'timeline': 'I want to be conversational in {0} months',
  'x_of_x': 'You got {0} correct.',
  'x_more_points': {
    'one': 'Earn {0} more point to reach your goal and keep the streak going!',
    'other': 'Earn {0} more points to reach your goal and keep the streak going!'
  },
  'start_streak': {
    'one': 'Earn {0} more point to reach your goal and start a streak!',
    'other': 'Earn {0} more points to reach your goal and start a streak!'
  },
  'reached_goal': {
    'one': 'You reached your daily goal {0} day in a row!',
    'other': 'You reached your daily goal {0} days in a row!'
  },
  'enable_quick_quiz': 'Quick Quiz',
  'enable_phonetics': 'Phonetics',
  'set_reminder': 'set reminder',
  'time_to_learn': 'Time to learn',
  'got_message': 'Someone has sent you a message',
  'thread_message': 'Unread Message',
  'volume_prompt': 'Low Volume Level',
  'explain_volume': 'Your volume is low, would you like us to turn it up for you?',
  'dont_show_again': "Don't show again",
  'explain_skip': 'Are you sure you already know this word? You will not see this word again until it is time to review.',
  'explain_ignore': 'Are you sure you want to ignore this word? You will not see this word again.',
  'disable_listen': 'Listening Quizzes',
  'explain_disable_listen': 'Are you sure you want to disable listening quizzes?',
  'disable_speak': 'Speaking Quizzes',
  'explain_disable_speak': 'Are you sure you want to disable speaking quizzes?',
  'language_exists': 'That language already exists, so we picked it for you.',
  'autocomplete': 'Autocomplete',
  'speakquiz': 'Speaking Quizzes',
  'listenquiz': 'Listening Quizzes',
  'tts_error': 'Text to Speech not properly functioning',
  'blankquiz': 'Fill in the Blank Quizzes',
  'imagequiz': 'Image Quizzes',
  match_the_image: 'Pick the matching image',
  'persian': 'Persian',
  'hebrew': 'Hebrew',
  'hindi': 'Hindi',
  'indonesian': 'Indonesian',
  'portuguese': 'Portuguese',
  'swedish': 'Swedish',
  'thai': 'Thai',
  'turkish': 'Turkish',
  'urdu': 'Urdu',
  'profile': 'Profile',
  'languages': 'Languages',
  'learn_a_new_language': 'Learn a new language',
  'percent_complete': '{0}% complete',
  'one_a_x_day_streak': 'One a {0} day streak',
  'cannot_learn_native': 'You cannot learn your native language',
  'support': 'Get Support',
  'fix_audio_title': 'Fix Audio',
  'fix_audio_message': 'In order for audio to work you must install and set the proper Text to Speech application. Would you like to install Google Text to Speech so that audio will work in this application?',
  'longest_streak': {
    'one': 'Longest streak : {0} day',
    'other': 'Longest streak : {0} days'
  },
  'bengali': 'Bengali',
  'czech': 'Czech',
  'danish': 'Danish',
  'dutch': 'Dutch',
  'filipino': 'Filipino',
  'finnish': 'Finnish',
  'gujrati': 'Gujarati',
  'slovak': 'Slovak',
  'telugu': 'Telugu',
  'vietnamese': 'Vietnamese',
  'tutorial_chapter': 'This is the learning center. Start out by choosing a chapter to learn from.',
  'tutorial_progress': 'Keep track of your progress here.',
  'tutorial_review': 'Click here to go to the review center.',
  'tutorial_review_options': 'Click here for all of the reviewing options.',
  'tutorial_settings': 'Click here view more options as well as other cool and new features.',
  'tutorial_lesson': 'Now choose a lesson to start learning.',
  'tutorial_learn': 'Click here for more learning options.',
  'requiresWifi': 'Download audio using wifi only',
  cancel: 'cancel',
  ok: 'ok',
  yes: 'yes',
  no: 'no',
  please_upgrade: 'Please click here to update to\nthe latest version of Lexicon',
  profile_required: 'Profile Required',
  explain_profile_required: 'This feature cannot be used unless you create a profile',
  not_now: 'later',
  you_are_making_progress: 'You are making progress!',
  you_have_completed_the_following: 'You have completed the following:',
  keep_going: 'keep going'
}
