export default {
  'threads': 'الخيوط',
  'tagline': 'رفيق تعلم اللغة',
  'get_started': 'ابدأ',
  'login': 'تسجيل الدخول',
  'or_str': 'أو',
  'connect_with_google': 'اتصل عبر جوجل',
  'connect_with_facebook': 'اتصل عبر فيسبوك',
  'what_native_language': 'ما هي لغتك الأم؟',
  'what_learning_language': 'ما هي اللغة التي تود تعلمها؟',
  'request_a_new_language': 'طلب لغة جديدة',
  'language': 'اللغة',
  'confirm': 'تأكيد',
  'what_score': 'ما مدى سرعة التعلم التي تريد؟',
  'offline_mode': 'وضع غير متصل بالشبكة',
  'explain_offline': 'يمكنك ذلك من تعلم الدروس بينما لا تكون متصلا بالإنترنت.',
  'download': 'تحميل',
  'search': 'بحث',
  'no_review': 'لا يوجد شيء لتراه هنا، انتقل إلى "تعلم" لتبدأ',
  'no_threads': 'لا يوجد شيء لتراه هنا، انتقل إلى "بحث" لتبدأ',
  'no_search': 'لا يوجد شيء لتراه هنا، عد في وقت لاحق لتحصل على المزيد من النتائج',
  'explain_settings': 'لحفظ عملك والوصول إلى الإعدادات، عليك إنشاء ملف شخصي',
  'create_profile': 'إنشاء ملف شخصي',
  'settings': 'الإعدادات',
  'test_favorites': 'اختبار المفضلة',
  'test_all': 'اختبار الكل',
  'audio': 'الصوت',
  'chapter': 'فصل',
  'exit_session': 'الخروج من الدرس',
  'explain_exit': 'أنت في درس الآن. هل أنت متأكد أنك تريد الخروج؟',
  'report': 'تقرير',
  'feedback': 'يرجى تقديم تعليق...',
  'ignore': 'تجاهل',
  'skip': 'تخطي',
  'tip': 'تلميح',
  'tip_for': 'تلميح عن:',
  'close': 'تم',
  'favorite': 'مفضلة',
  'continue_str': 'مواصلة',
  'you_mastered': 'لقد أتقنت الدرس!',
  'earned_point': 'لقد حصلت على نقطة لإجابتك إجابات صحيحة عن كل الأسئلة!',
  'explain_points': 'للبدء في إحراز النقاط والحصول على شارات، عليك إنشاء ملف شخصي.',
  'keep_reviewing': 'واصل المراجعة',
  'keep_learning': 'واصل التعلم',
  'back_to_overview': 'عودة إلى النظرة العامة',
  'back_to_lessons': 'عودة إلى الدروس',
  'translate_this_phrase': 'ترجم هذه العبارة',
  'record_the_translation': 'سجل الترجمة',
  'pick_the_translation': 'اختر الترجمة الصحيحة',
  'enable_images': 'تنزيل الصور',
  'clear_data': 'امسح كافة بينات التطبيق',
  'are_you_sure': 'هل أنت متأكد',
  'explain_clear': 'أنت على وشك مسح كل البيانات. لا يمكن التراجع عن هذا الإجراء.',
  'check': 'تفقد',
  'translate': 'ترجم',
  'name': 'اسم',
  'review': 'مراجعة',
  'lesson': 'درس',
  'you_are_correct': 'إجابتك صحيحة',
  'you_are_incorrect': 'معذرة، الإجابة غير صحيحة',
  'feedback_please': 'يرجى تزويدنا بمعلومات مفصلة حول المشكلة.',
  'complete': 'اكتمل',
  'all_for_master': 'يجب أن تكون كل إجاباتك صحيحة لكي تتقن هذا الدرس.',
  'all_for_point': 'يجب أن تكون كل إجاباتك صحيحة لكي تحرز نقطة.',
  'search_vocab': 'ابحث في جميع المفردات',
  'email': 'البريد الإلكتروني',
  'password': 'كلمة المرور',
  'try_again': 'حاول مرة أخرى.',
  'provide_language': 'يرجى إدخال اسم اللغة التي ترغب في أن نضيفها',
  'welcome_back': 'مرحبا بعودتك!',
  'what_do_you_think': 'ما رأيك في القاموس؟',
  'i_like_it': 'أحبه',
  'i_dont_like_it': 'يحتاج إلى تطوير',
  'thats_great': 'هذا رائع!',
  'rate_explain': 'هل تود تقييم التطبيق وكتابة تعليق. لن يستغرق ذلك الكثير من الوقت وسيساعد في إضافة المزيد من الميزات قريبا.',
  'sure': 'بالتأكيد',
  'later': 'في وقت لاحق',
  'never': 'أبدا',
  'arabic': 'العربية',
  'catalan': 'الكاتالونية',
  'chinese_cantonese': 'الصينية - الكانتونية',
  'chinese_mandarin': 'الصينية - الماندرين',
  'english': 'الإنجليزية',
  'german': 'الألمانية',
  'greek': 'اليونانية',
  'italian': 'الإيطالية',
  'french': 'الفرنسية',
  'japanese': 'اليابانية',
  'korean': 'الكورية',
  'polish': 'البولندية',
  'russian': 'الروسية',
  'spanish': 'الأسبانية',
  'learn': 'تعلم',
  'error': 'القاموس تعطل',
  'thank_you': 'شكرا على تعليقك!',
  'cannot_connect': 'لا يمكن الاتصال بالخادم',
  'uh_oh': 'أوه، يبدو أن القاموس قد تعطل',
  'restart_and_report': 'أعد التشغيل وأرسل تقرير',
  'chat': 'دردشة',
  'thanks_again': 'شكرا على طلبك. سوف نحاول إضافة هذه اللغة في أقرب وقت ممكن.',
  'click_to_respond': 'اضغط لإعادة الإرسال',
  'thread': 'خيط',
  'unsent': 'غير مرسل',
  'points_per_day': '{0} نقاط يوميا',
  'timeline': 'أريد أن أتحدث بطلاقة خلال {0} أشهر',
  'x_of_x': 'لقد أجبت على {0} أسئلة بنجاح.',
  'x_more_points': '',
  'start_streak': '',
  'reached_goal': '',
  'enable_quick_quiz': 'اختبار قصير',
  'enable_phonetics': 'الصوتيات',
  'set_reminder': 'ضبط التذكير',
  'time_to_learn': 'حان وقت التعلم',
  'become_fluent': 'تحدث بطلاقة خلال 3 أشهر بالتعلم لمدة 10 دقائق فقط في اليوم!',
  'got_message': 'أحدهم أرسل لك رسالة',
  'thread_message': 'رسالة غير مقروءة',
  'volume_prompt': 'مستوى الصوت منخفض',
  'explain_volume': 'مستوى الصوت منخفض، هل تريدنا أن نرفع مستوى الصوت؟',
  'dont_show_again': 'لا تظهر مرة أخرى',
  'explain_skip': 'هل أنت متأكد أنك تعرف هذه الكلمة بالفعل؟ لن ترى هذه الكلمة مرة أخرى حتى يحين وقت المراجعة.',
  'explain_ignore': 'هل أنت متأكد أنك تريد تجاهل هذه الكلمة؟ لن ترى هذه الكلمة مرة أخرى.',
  'disable_listen': 'اختبارات استماع',
  'explain_disable_listen': 'هل أنت متأكد أنك تريد تعطيل اختبارات السماع؟',
  'disable_speak': 'اختبارات تحدث',
  'explain_disable_speak': 'هل أنت متأكد أنك تريد تعطيل اختبارات التحدث؟',
  'language_exists': 'هذه اللغة موجودة بالفعل، لذلك اخترناها لك.',
  'autocomplete': 'إكمال تلقائي',
  'speakquiz': 'اختبارات تحدّث',
  'listenquiz': 'اختبارات استماع',
  'tts_error': 'تحويل النص إلى كلام لا يعمل بشكل صحيح',
  'blankquiz': 'املأ الاختبارات الفارغة',
  'persian': 'الفارسية',
  'hebrew': 'العبرية',
  'hindi': 'الهندية',
  'indonesian': 'الأندونيسية',
  'portuguese': 'البرتغالية',
  'swedish': 'السويدية',
  'thai': 'التايلاندية',
  'turkish': 'التركية',
  'urdu': 'الأردية',
  'profile': 'الملف الشخصي',
  'languages': 'اللغات',
  'learn_a_new_language': 'تعلم لغة جديدة',
  'please_double_check': 'يمكنك تحريك القائمة من خلال الفأرة، تأكد من أن اللغة التي تهتم بها غير موجودة. وتأكد أيضا أنك اخترت اللغة الصحيحة، وإن لم تفعل فاضغط على عودة للمحاولة مرة أخرى. وإذا كنت متأكدا أن اللغة التي ترغب فيها عير موجودة، فاضغط على زر "طلب لغة جديدة" مرة أخرى.',
  'percent_complete': 'اكتمال بنسبة {0} % c',
  'one_a_x_day_streak': 'سلسلة واحدة كل {0} أيام',
  'longest_streak': '',
  'cannot_learn_native': 'You cannot learn your native language',
  'support': 'Support',
  'fix_audio_title': 'Fix Audio',
  'fix_audio_message': 'In order for audio to work you must install a Text to Speech application. Would you like to download Google Text to Speech so that audio will work in this application?',
  'bengali': 'Bengali',
  'czech': 'Czech',
  'danish': 'Danish',
  'dutch': 'Dutch',
  'filipino': 'Filipino',
  'finnish': 'Finnish',
  'gujrati': 'Gujarati',
  'slovak': 'Slovak',
  'telugu': 'Telugu',
  'vietnamese': 'Vietnamese',
  'please_upgrade': 'Please click here to update to the latest version of Lexicon',
  'tutorial_chapter': 'This is the learning center. Start out by choosing a chapter to learn from.',
  'tutorial_progress': 'Keep track of your progress here.',
  'tutorial_review': 'Click here to go to the review center.',
  'tutorial_review_options': 'Click here for all of the reviewing options.',
  'tutorial_settings': 'Click here view more options as well as other cool and new features.',
  'tutorial_lesson': 'Now choose a lesson to start learning.',
  'tutorial_learn': 'Click here for more learning options.'
}
