export default { threads: '主题',
  tagline: '语言学习好友',
  get_started: '开始',
  login: '登录',
  or_str: '或者',
  connect_with_google: '用GOOGLE 连接',
  connect_with_facebook: '用FACEBOOK 连接',
  what_native_language: '您的母语是什么？',
  what_learning_language: '您想要学习什么语言？',
  request_a_new_language: '申请一门新语言',
  language: '语言',
  confirm: '确认',
  what_score: '您需要以什么样的速度学习？',
  offline_mode: '离线模式',
  explain_offline: '这可以让您在没有网络连接的环境下也能学习一节课。',
  download: '下载',
  search: '搜索',
  no_review: '这里没什么可看的，进入学习并开始吧',
  no_threads: '这里没什么可看的，进入搜索并开始吧',
  no_search: '这里没什么可看的，稍后回来查看更多结果吧',
  explain_settings: '要想保存您的工作并访问设置，您需要创建一份个人资料',
  create_profile: '创建个人资料',
  settings: '设置',
  test_favorites: '测试收藏',
  test_all: '测试全部',
  audio: '音频',
  chapter: '章节',
  exit_session: '退出课程',
  explain_exit: '您正在课程之中。您确定要退出吗？',
  report: '报告',
  feedback: '请提供反馈...',
  ignore: '忽视',
  skip: '跳过',
  tip: '提示',
  tip_for: '提示为：',
  close: '完成',
  favorite: '收藏',
  continue_str: '继续',
  you_mastered: '您已经掌握了这节课！',
  earned_point: '您答对了每一题，因此获得了1分！',
  explain_points: '要开始获得分数和奖章，您必须创建一份个人资料。',
  keep_reviewing: '继续回顾',
  keep_learning: '继续学习',
  back_to_overview: '回到概述',
  back_to_lessons: '回到课程',
  translate_this_phrase: '翻译这个短语',
  record_the_translation: '继续翻译',
  pick_the_translation: '选择正确的翻译',
  enable_images: '下载图片',
  clear_data: '清除所有应用数据',
  are_you_sure: '您确定吗',
  explain_clear: '您将要清除所有的应用数据。这一操作无法复原。',
  check: '检查',
  translate: '翻译',
  name: '名称',
  review: '回顾',
  lesson: '课程',
  you_are_correct: '您回答正确',
  you_are_incorrect: '哎呀，答错了',
  feedback_please: '请提供详细的问题反馈。',
  complete: '完成',
  all_for_master: '您需要正确回答所有问题才能掌握这节课。',
  all_for_point: '您需要正确回答所有问题才能赢得1分。',
  search_vocab: '搜索所有词汇',
  email: 'Email',
  password: '密码',
  try_again: '请再试一次。',
  provide_language: '请提供您希望我们添加的语言名称。',
  welcome_back: '欢迎回来！',
  what_do_you_think: '目前为止您觉得Lexicon 如何？',
  i_like_it: '我喜欢',
  i_dont_like_it: '它需要改进',
  thats_great: '太棒了！',
  rate_explain: '您愿意评价我们的应用并留下一则评论吗？它并不需要很长时间，而且可以帮助我们更快推出新功能。',
  sure: '当然',
  later: '以后',
  never: '决不',
  arabic: '阿拉伯语',
  catalan: '加泰罗尼亚语',
  chinese_cantonese: '中文 - 粤语',
  chinese_mandarin: '中文 - 普通话',
  english: '英语',
  german: '德语',
  greek: '希腊语',
  italian: '意大利语',
  french: '法语',
  japanese: '日语',
  korean: '韩语',
  polish: '波兰语',
  russian: '俄语',
  spanish: '西班牙语',
  learn: '学习',
  error: 'Lexicon 崩溃了',
  thank_you: '感谢您的反馈意见！',
  cannot_connect: '无法连接到服务器',
  uh_oh: '啊哦，Lexicon 好像崩溃了',
  restart_and_report: '重新启动并发送报告',
  chat: '聊天',
  thanks_again: '感谢您的要求。我们将会尝试尽快添加这门语言。',
  click_to_respond: '点击重新发送',
  thread: '主题',
  unsent: '未发送',
  points_per_day: '{0}分/天',
  timeline: '我想要在{0} 个月内达到流利',
  x_of_x: '你答对了{0}。',
  x_more_points: '',
  start_streak: '',
  reached_goal: '',
  enable_quick_quiz: '快速测验',
  enable_phonetics: '语音',
  set_reminder: '设置提醒',
  time_to_learn: '时间学习',
  become_fluent: '在3个月内达到流利，每天只需10分钟！',
  got_message: '有人向您发送了一条消息',
  thread_message: '未读消息',
  volume_prompt: '低音量',
  explain_volume: '您的音量很低，您想让我们将其提高吗？',
  dont_show_again: '不再显示',
  explain_skip: '您确定您已经认识这个单词了？直到回顾时间之前，您将不会再看见这个单词。',
  explain_ignore: '您确定要忽略这个单词？您将不会再看见这个单词。',
  disable_listen: '听力测验',
  explain_disable_listen: '您确定要禁用听力测验？',
  disable_speak: '口语测验',
  explain_disable_speak: '您确定要禁用口语测验？',
  language_exists: '该语言已经存在，所以我们为您选择了它。',
  autocomplete: '自动补全',
  speakquiz: '口语测验',
  listenquiz: '听力测验',
  tts_error: '文本至语音功能不正常',
  blankquiz: '填写空白测验题',
  persian: '波斯语',
  hebrew: '希伯来语',
  hindi: '印地语',
  indonesian: '印度尼西亚语',
  portuguese: '葡萄牙语',
  swedish: '瑞典语',
  thai: '泰语',
  turkish: '土耳其语',
  urdu: '乌尔都语',
  profile: '个人资料',
  languages: '语言',
  learn_a_new_language: '学习一门新语言',
  please_double_check: '滚动查看列表，务必确定您感兴趣的语言是否存在。另外，还要确保选择正确的母语，如果没有，请按返回再试一次。如果您确定您感兴趣的语言不存在，请再次单击“请求新语言”按钮。',
  percent_complete: '{0}% c完成',
  one_a_x_day_streak: '连续${0}天',
  longest_streak: '',
  cannot_learn_native: 'You cannot learn your native language',
  support: 'Support',
  fix_audio_title: 'Fix Audio',
  fix_audio_message: 'In order for audio to work you must install a Text to Speech application. Would you like to download Google Text to Speech so that audio will work in this application?',
  bengali: 'Bengali',
  czech: 'Czech',
  danish: 'Danish',
  dutch: 'Dutch',
  filipino: 'Filipino',
  finnish: 'Finnish',
  gujrati: 'Gujarati',
  slovak: 'Slovak',
  telugu: 'Telugu',
  vietnamese: 'Vietnamese',
  please_upgrade: 'Please click here to update to the latest version of Lexicon',
  tutorial_chapter: 'This is the learning center. Start out by choosing a chapter to learn from.',
  tutorial_progress: 'Keep track of your progress here.',
  tutorial_review: 'Click here to go to the review center.',
  tutorial_review_options: 'Click here for all of the reviewing options.',
  tutorial_settings: 'Click here view more options as well as other cool and new features.',
  tutorial_lesson: 'Now choose a lesson to start learning.',
  tutorial_learn: 'Click here for more learning options.' }
