export default { threads: 'Enlaces',
  tagline: 'Amigo para aprender idiomas',
  get_started: 'comenzar',
  login: 'Iniciar sesión',
  or_str: 'o',
  connect_with_google: 'CONECTAR CON GOOGLE',
  connect_with_facebook: 'CONECTAR CON FACEBOOK',
  what_native_language: '¿Qué idioma hablas de forma nativa?',
  what_learning_language: '¿Qué idioma te gustaría aprender?',
  request_a_new_language: 'Solicitar un nuevo idioma',
  language: 'Idioma',
  confirm: 'confirmar',
  what_score: '¿Con qué rapidez te gustaría aprender?',
  offline_mode: 'Modo sin conexión',
  explain_offline: 'Esto te permite aprender de una lección mientras no estás conectado a Internet.',
  download: 'Descargar',
  search: 'buscar',
  no_review: 'No hay nada que ver aquí, ve a Aprender para comenzar',
  no_threads: 'No hay nada que ver aquí, ve a Buscar para comenzar',
  no_search: 'No hay nada que ver aquí, vuelve más tarde para obtener más resultados',
  explain_settings: 'Para guardar tu trabajo y acceder a los ajustes debes crear un perfil',
  create_profile: 'Crear perfil',
  settings: 'Ajustes',
  test_favorites: 'Probar favoritos',
  test_all: 'Probar todos',
  audio: 'Audio',
  chapter: 'Capítulo',
  exit_session: 'Salir de la sesión',
  explain_exit: 'Estás a la mitad de una sesión. ¿Seguro que quieres salir?',
  report: 'Reportar',
  feedback: 'Por favor proporciona tus comentarios...',
  ignore: 'Ignorar',
  skip: 'Omitir',
  tip: 'Consejo',
  tip_for: 'Consejo para:',
  close: 'hecho',
  favorite: 'Favorito',
  continue_str: 'continuar',
  you_mastered: '¡Has dominado la lección!',
  earned_point: '¡Has ganado un punto por responder todas las preguntas correctamente!',
  explain_points: 'Para comenzar a ganar puntos e insignias debes crear un perfil.',
  keep_reviewing: 'seguir revisando',
  keep_learning: 'seguir aprendiendo',
  back_to_overview: 'regresar a la visita general',
  back_to_lessons: 'regresar a las lecciones',
  translate_this_phrase: 'Traduce esta frase',
  record_the_translation: 'Registrar la traducción',
  pick_the_translation: 'Elige la traducción correcta',
  enable_images: 'Descargar imágenes',
  clear_data: 'BORRAR TODOS LOS DATOS DE LA APP',
  are_you_sure: '¿Estás seguro?',
  explain_clear: 'Estás a punto de borrar todos los datos de la aplicación. Esta acción no puede deshacerse.',
  check: 'verificar',
  translate: 'traducir',
  name: 'Nombre',
  review: 'Revisión',
  lesson: 'Lección',
  you_are_correct: 'Estás en lo correcto',
  you_are_incorrect: 'Ups, eso no es correcto',
  feedback_please: 'Por favor proporciona comentarios detallados sobre el problema.',
  complete: 'Completar',
  all_for_master: 'Debes tener todas las respuestas correctas para dominar esta lección.',
  all_for_point: 'Debes tener todas las respuestas correctas para ganar un punto.',
  search_vocab: 'Buscar todo el vocabulario',
  email: 'Correo electrónico',
  password: 'Contraseña',
  try_again: 'Por favor inténtalo de nuevo.',
  provide_language: 'Por favor indica el nombre del idioma que te gustaría que añadiéramos.',
  welcome_back: '¡Bienvenido de nuevo!',
  what_do_you_think: '¿Qué opinas de Lexicon hasta ahora?',
  i_like_it: 'Me gusta',
  i_dont_like_it: 'Debe mejorar',
  thats_great: '¡Genial!',
  rate_explain: '¿Te gustaría calificar la aplicación y dejar un comentario? No toma mucho tiempo y ayudará para añadir nuevas funciones pronto.',
  sure: '¡Claro!',
  later: 'Más tarde',
  never: 'Nunca',
  arabic: 'Árabe',
  catalan: 'Catalán',
  chinese_cantonese: 'Chino - Cantonés',
  chinese_mandarin: 'Chino - Mandarín',
  english: 'Inglés',
  german: 'Alemán',
  greek: 'Griego',
  italian: 'Italiano',
  french: 'Francés',
  japanese: 'Japonés',
  korean: 'Coreano',
  polish: 'Polaco',
  russian: 'Ruso',
  spanish: 'Español',
  learn: 'aprender',
  error: 'Lexicon no funciona',
  thank_you: '¡Gracias por tus comentarios!',
  cannot_connect: 'No se puede conectar con el servidor',
  uh_oh: 'Uh oh, al parecer Lexicon ha dejado de funcionar',
  restart_and_report: 'Reiniciar y enviar informe',
  chat: 'Chat',
  thanks_again: 'Gracias por tu solicitud. Trataremos de añadir ese idioma tan pronto como sea posible.',
  click_to_respond: 'Haz clic para reenviar',
  thread: 'Enlace',
  unsent: 'NO ENVIADO',
  points_per_day: '{0} puntos por día',
  timeline: 'Deseo tener fluidez en {0} meses',
  x_of_x: 'Tienes {0} correctas.',
  x_more_points: '',
  start_streak: '',
  reached_goal: '',
  enable_quick_quiz: 'Cuestionario rápido',
  enable_phonetics: 'Fonética',
  set_reminder: 'definir recordatorio',
  time_to_learn: 'Hora de aprender',
  become_fluent: '¡Ten fluidez en 3 meses con solo 10 minutos por día!',
  got_message: 'Alguien te ha enviado un mensaje',
  thread_message: 'Mensajes no leídos',
  volume_prompt: 'Nivel de volumen bajo',
  explain_volume: 'El volumen está demasiado bajo. ¿Deseas que lo subamos para ti?',
  dont_show_again: 'No mostrar de nuevo',
  explain_skip: '¿Estás seguro que ya sabes esta palabra? No verás esta palabra de nuevo hasta que sea hora de repasar.',
  explain_ignore: '¿Estás seguro que deseas ignorar esta palabra? No verás esta palabra de nuevo.',
  disable_listen: 'Cuestionarios de comprensión auditiva',
  explain_disable_listen: '¿Estás seguro que deseas deshabilitar los cuestionarios de comprensión auditiva?',
  disable_speak: 'Cuestionarios de expresión oral',
  explain_disable_speak: '¿Estás seguro que deseas deshabilitar los cuestionarios de expresión oral?',
  language_exists: 'Ese idioma ya existe, así que lo elegimos para ti.',
  autocomplete: 'Autocompletar',
  speakquiz: 'Cuestionarios de expresión oral',
  listenquiz: 'Cuestionarios de comprensión auditiva',
  tts_error: 'La función de texto a voz no funciona correctamente',
  blankquiz: 'Completa los cuestionarios en blanco',
  persian: 'Persa',
  hebrew: 'Hebreo',
  hindi: 'Hindi',
  indonesian: 'Indonesio',
  portuguese: 'Portugués',
  swedish: 'Sueco',
  thai: 'Tailandés',
  turkish: 'Turco',
  urdu: 'Urdu',
  profile: 'Perfil',
  languages: 'Idiomas',
  learn_a_new_language: 'Aprender un nuevo idioma',
  please_double_check: 'La lista se desplaza, por lo tanto, asegúrate que el idioma que te interesa no exista. Igualmente, asegúrate de haber elegido el idioma nativo correcto, si no, presiona Atrás para intentar de nuevo. Si estás seguro que el idioma que te interesa no existe, haz clic de nuevo en el botón "Solicitar un nuevo idioma".',
  percent_complete: '{0}% completo',
  one_a_x_day_streak: 'Una racha de {0} día',
  longest_streak: '',
  cannot_learn_native: 'You cannot learn your native language',
  support: 'Support',
  fix_audio_title: 'Fix Audio',
  fix_audio_message: 'In order for audio to work you must install a Text to Speech application. Would you like to download Google Text to Speech so that audio will work in this application?',
  bengali: 'Bengali',
  czech: 'Czech',
  danish: 'Danish',
  dutch: 'Dutch',
  filipino: 'Filipino',
  finnish: 'Finnish',
  gujrati: 'Gujarati',
  slovak: 'Slovak',
  telugu: 'Telugu',
  vietnamese: 'Vietnamese',
  please_upgrade: 'Please click here to update to the latest version of Lexicon',
  tutorial_chapter: 'This is the learning center. Start out by choosing a chapter to learn from.',
  tutorial_progress: 'Keep track of your progress here.',
  tutorial_review: 'Click here to go to the review center.',
  tutorial_review_options: 'Click here for all of the reviewing options.',
  tutorial_settings: 'Click here view more options as well as other cool and new features.',
  tutorial_lesson: 'Now choose a lesson to start learning.',
  tutorial_learn: 'Click here for more learning options.' }
